### ISSUE TITLE
Support for WebClientSession

### ISSUE THREAD

**Issue by sbeigel** [smallrye/smallrye-mutiny-vertx-bindings#244]
Title says it all :) It would be great to have a Mutiny version of Vert.x' WebClientSession in Quarkus to mimic the usage of WebClient but with session support (i.e. using a cookie store).

**Comment by cescoffier** [comment]
The class is not generated because the original class (from Vert.x Web) is not annotated with @VertxGen. I just opened an issue.

**Comment by cescoffier** [comment]
This has been fixed. We are generating `io.vertx.mutiny.ext.web.client.WebClientSession`.
