### ISSUE TITLE
Microsoft SQL Server support

### ISSUE THREAD

**Issue by GoGoris** [smallrye/smallrye-mutiny-vertx-bindings#278]
Microsoft SQL Server support has been added in vertx 4, would it be a lot of work to support this in mutiny as well?

https://github.com/eclipse-vertx/vertx-sql-client/tree/master/vertx-mssql-client

**Comment by tsegismont** [comment]
@GoGoris Microsoft SQL Server support is still a WIP. We (the Vert.x team) want to make the first release of the Reactive SQL Server Client in Vert.x 4.1. Which we hope is a few months ahead.

**Comment by jponge** [comment]
Once the driver is ready in Vert.x we can definitely add a Mutiny binding.

**Comment by GoGoris** [comment]
Thank you for the info, keep up the great work!
