### ISSUE TITLE
Rename to smallrye-vertx-mutiny?

### ISSUE THREAD

**Issue by jponge** [smallrye/smallrye-mutiny-vertx-bindings#331]
As part of #315 I'm thinking that we may simply publish documentation from this repository.

Shouldn't we rename this repository to `smallrye-vertx-mutiny` or anything similar? The main driver for this repository is to publish the Vert.x Mutiny bindings anyway.

**Comment by kenfinnigan** [comment]
I'm fine with a rename

**Comment by cescoffier** [comment]
I'm fine with the rename. `smallrye-vertx-mutiny` is slightly confusing as we can read it as `smallrye-vertx`. But I don't have a better proposal :-D

**Comment by jponge** [comment]
Alternatively how about `smallrye-mutiny-vertx`?

**Comment by kenfinnigan** [comment]
Only issue I just thought of is whether the possible new names cause confusion with the reactive converters module.

Should the reactive converters stay in this project, which are then utils, and have a separate project for the Mutiny Vert.x clients? Or are the two reliant on each other?

**Comment by jponge** [comment]
Indeed we might split repos, WDYT @cescoffier @radcortez?

**Comment by Ladicek** [comment]
Usually, when something is called "utils", its purpose is not clear. Just split this repo into two: `smallrye-reactive-converters` and `smallrye-mutiny-vertx-bindings`.

**Comment by jponge** [comment]
That's good idea

**Comment by cescoffier** [comment]
Yes, we should split. 

About the name `smallrye-mutiny-vertx-bindings` might be clearer.

**Comment by jponge** [comment]
> Yes, we should split.
> 
> About the name `smallrye-mutiny-vertx-bindings` might be clearer.

✅

**Comment by jponge** [comment]
@radcortez Should you create the repos and I migrate code, or can I just do it and CI/CD credentials are org-wide?

**Comment by cescoffier** [comment]
I've renamed this repo - I have the karma to do that.

@radcortez can you create the `smallrye-reactive-converters` repository

**Comment by radcortez** [comment]
> @radcortez Should you create the repos and I migrate code, or can I just do it and CI/CD credentials are org-wide?

The credential are org-wide. Feel free to move on.

> @radcortez can you create the `smallrye-reactive-converters` repository

Sure.

**Comment by radcortez** [comment]
Done: https://github.com/smallrye/smallrye-reactive-converters

**Comment by jponge** [comment]
@cescoffier Ok if I arrange the code split between the 2 repos, or do you want to make the one for `smallrye-reactive-converters`

**Comment by jponge** [comment]
- [ ] Transplant reactive converters code
- [ ] Remove reactive converters from this repository

**Comment by jponge** [comment]
> @jponge up to you, I can handle smallrye-reactive-converters tonight if you need.

Looks like it's ok as I did. I did not remove the top-level Maven parent module though

**Comment by jponge** [comment]
@cescoffier There'll be the Sonar setup to sync since the repo has been renamed

**Comment by cescoffier** [comment]
I don't believe the sonar build ran for the last few months.

**Comment by jponge** [comment]
I consider it done!
