### ISSUE TITLE
Code generation resulting in import conflict

### ISSUE THREAD

**Issue by jponge** [smallrye/smallrye-mutiny-vertx-bindings#341]
Spotted with 1 case in Mutiny-fying https://github.com/reactiverse/elasticsearch-client

See:

* https://gist.github.com/jponge/1e8784dbeddf9d0b6d7176489c147b03#file-generated-java-L72 source and generated code with the issue
* https://github.com/reactiverse/elasticsearch-client/pull/11 pull request with the reproducer

**Comment by cescoffier** [comment]
2 imports, same name:
```
import org.elasticsearch.action.support.master.AcknowledgedResponse;
import import org.elasticsearch.client.core.AcknowledgedResponse;
```

**Comment by jponge** [comment]
Yes, the other code generators do not have this problem.
