### ISSUE TITLE
Check the status of the com.ongres.scram:client:2.1  dependency in the Pg client bindings

### ISSUE THREAD

**Issue by jponge** [smallrye/smallrye-mutiny-vertx-bindings#404]

**Comment by jponge** [comment]
See https://github.com/smallrye/smallrye-mutiny-vertx-bindings/pull/403/commits/7785f83ce152fcb42f16cc0742e20d286b60c69a

**Comment by cescoffier** [comment]
It seems to be mandatory as it's the library handling authentication. As accessing an unauthenticated PG database is rare, I would say that this dependency must not be optional.
