### ISSUE TITLE
Binding for AWS SQS

### ISSUE THREAD

**Issue by MihaiBogdanEugen** [smallrye/smallrye-mutiny-vertx-bindings#452]
Can we have bindings for AWS SQS using the v2 of the AWS Java SDK? The v2 is embracing non-blocking IO model, so it should be good to go.

**Comment by cescoffier** [comment]
The bindings generated by this project are based on Vert.x APIs. For SQS, we don't have a Vert.x API. 
It does not mean we cannot do it, however, it will not follow the same process, as we would have to produce an API and keep track of all upstream changes (from the AWS SQS client).
