### ISSUE TITLE
Mutiny's version of WebClientSession is missing the constructor that takes a CookieStore and the cookieStore() getter

### ISSUE THREAD

**Issue by Ultranium** [smallrye/smallrye-mutiny-vertx-bindings#489]
The Mutiny's WebClientSession binding is missing the constructor that takes a CookieStore and the cookieStore() getter which [the original Vert.x WebClientSession](url) has.

Because of this, there is no easy way to manage session cookies.

I'm using the smallrye-mutiny-vertx-web-client v2.18.1

**Comment by cescoffier** [comment]
This should be reported in the Vert.x repository as the method should be marked as `@GenIgnore`. Can you open the issue in Vert.x Web?

**Comment by Ultranium** [comment]
Sure, I'll report to the Vert.x repo.
