### ISSUE TITLE
Codegen imports unused classes

### ISSUE THREAD

**Issue by jklingsporn** [smallrye/smallrye-mutiny-vertx-bindings#492]
While I was playing around with the generator, I figured out that for all generated classes the same mandatory imports are generated - no matter what:
https://github.com/smallrye/smallrye-mutiny-vertx-bindings/blob/dda664c3fb94bbeeb0e763fd088ff6fb357d1a4b/vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/lang/ImportDeclarationCodeWriter.java#L24-L34
Unfortunately, I have an interface called `Publisher` which I annotated with `@VertxGen` and it clashes with `org.reactivestreams.Publisher` - even if it is not used in the generated class. 

Any ideas of how to fix this (besides renaming my Interface)?

**Comment by zero88** [comment]
Another relating issue is: 
import redundant classes/interfaces that are declared in origin class but are in package level access => complied failed

**Comment by cescoffier** [comment]
Can you give an example of that?

**Comment by zero88** [comment]
Origin class `JooqxBuilder`. `SQLExecutorBuilder` is the internal interface (package level)

```java
import org.jetbrains.annotations.NotNull;
import org.jooq.DSLContext;

import io.github.zero88.jooqx.datatype.DataTypeMapperRegistry;
import io.vertx.codegen.annotations.Fluent;
import io.vertx.codegen.annotations.GenIgnore;
import io.vertx.codegen.annotations.VertxGen;
import io.vertx.core.Vertx;
import io.vertx.sqlclient.Pool;
import io.vertx.sqlclient.Row;
import io.vertx.sqlclient.RowSet;
import io.vertx.sqlclient.Tuple;

/**
 * Represents a builder that constructs {@link Jooqx}
 *
 * @since 2.0.0
 */
@VertxGen
public interface JooqxBuilder extends SQLExecutorBuilder {
```

Generated class
```java
import java.util.Map;
import java.util.stream.Collectors;
import io.smallrye.mutiny.Multi;
import io.smallrye.mutiny.Uni;
import java.util.function.Consumer;
import org.reactivestreams.Subscriber;
import org.reactivestreams.Publisher;
import io.smallrye.mutiny.vertx.TypeArg;
import io.vertx.codegen.annotations.Fluent;
import io.smallrye.common.annotation.CheckReturnValue;
import io.github.zero88.jooqx.SQLExecutorBuilder;
import io.github.zero88.jooqx.datatype.DataTypeMapperRegistry;
import org.jooq.DSLContext;
import io.github.zero88.jooqx.SQLErrorConverter;

/**
 * Represents a builder that construct {@link io.github.zero88.jooqx.mutiny.Jooqx}
 *
 * <p/>
 * NOTE: This class has been automatically generated from the {@link io.github.zero88.jooqx.JooqxBuilder original} non Mutiny-ified interface using Vert.x codegen.
 */

@io.smallrye.mutiny.vertx.MutinyGen(io.github.zero88.jooqx.JooqxBuilder.class)
public class JooqxBuilder {
```

This issue does not happen with `vertx-rx3` and `vertx-rx2`

**Comment by cescoffier** [comment]
I will fix the Publisher issue, but the visibility issue is more complex. I've to see what the other generators are doing, but yes, for now, it's a Mutiny generator limitation (do not forget that this generator is very different from the RX ones and does a lot more). 

Can you open a new issue with to address the visibility issue?
