### ISSUE TITLE
OAuth2AuthHandler is not setting the scopes correctly

### ISSUE THREAD

**Issue by schlumpfling42** [smallrye/smallrye-mutiny-vertx-bindings#502]
I'm trying to set the scopes with
			OAuth2AuthHandler handler = OAuth2AuthHandler.create(vertx, authProvider, "http://" + hostname + ":" + port  + authenticationProviderConfiguration.callbackPath())
					.withScopes(Arrays.asList("email", "profile"))

but the scopes are ignored.

I looked a the implementation of withScopes implemented:
  @Fluent
  public io.vertx.mutiny.ext.web.handler.OAuth2AuthHandler withScopes(List<String> scopes) { 
    delegate.withScopes(scopes);
    return this;
  }

And then at the delegate implementation and that is not setting the scopes, it's creating a new instance that has the new scope:
  @Override
  public OAuth2AuthHandler withScopes(List<String> scopes) {
    return new OAuth2AuthHandlerImpl(this, scopes);
  }

So the implementation should be:

  @Fluent
  public io.vertx.mutiny.ext.web.handler.OAuth2AuthHandler withScopes(List<String> scopes) { 
    delegate = delegate.withScopes(scopes);
    return this;
  }

**Comment by cescoffier** [comment]
That's a bug in Vert.x Auth. Can you report it in https://github.com/vert-x3/vertx-auth?

The code you reference is automatically generated from vert.x auth.
