### ISSUE TITLE
Mutiny version of io.vertx.ext.web.client.impl.MultipartFormUpload?

### ISSUE THREAD

**Issue by cameronprater** [smallrye/smallrye-mutiny-vertx-bindings#678]
I found a somewhat hacky way to construct a `MultiReadStream` from this class, but the resulting `Multi` never completes no matter what data is passed into the form. I assume it's an incompatibility between the way `MultipartFormUpload` is used and the way that `MultiReadStream` adapts `ReadStream`. I am trying to send a multipart request body from `HttpClient` and I can't use `WebClient` because I need websocket support. So how can I achieve this using Mutiny bindings? 

Here's how I'm constructing the `Multi`:
```java
MultiMap headers = ...;
MultipartForm form = MultipartForm.create();

// add files

MultipartFormUpload upload;
try {
  upload = new MultipartFormUpload(vertx.getOrCreateContext().getDelegate(), form.getDelegate(), true, EncoderMode.HTML5);
} catch (Exception e) {
  throw new RuntimeException(e);
}

headers.addAll(MultiMap.newInstance(upload.headers()));
return ReadStream.newInstance(upload).toMulti();
```

**Comment by cescoffier** [comment]
We have a Mutiny variant of `io.vertx.ext.web.multipart.MultipartForm`:
`https://smallrye.io/smallrye-mutiny-vertx-bindings/3.2.0/apidocs/io/vertx/mutiny/ext/web/multipart/MultipartForm.html`

It provides a `toMulti` method.

**Comment by cameronprater** [comment]
I've seen that, but it dosen't handle actually encoding the request, right? You can get the file contents from this, but it doesn't handle the request like `MultipartFormUpload` which handles chunking the request to the server, setting `Content-Disposition` headers on subparts and writing form boundaries. I can manually handle the request using this if needed, just hoping there was another option.

**Comment by cescoffier** [comment]
I didn't look in detail, but the toMulti should provide what you need as it follows the stream semantic.
