### ISSUE TITLE
why do you use Vertx

### ISSUE THREAD

**Issue by FishingZVVZ** [smallrye/smallrye-mutiny-vertx-bindings#684]
Hi, Why do you use Vertx, are you using reactive programming, why dont you use Webflux in Spring. What is the difference between Vertx and Webflux when talking about Reactive Programming

**Comment by jponge** [comment]
- Mutiny is reactive programming library. It is agnostic to the underlying I/O / network library.
- Vert.x is a proven and versatile toolkit for writing all kinds of reactive applications.
- This repository is explicitly about providing _Mutiny bindings_ for the Vert.x core APIs.
