### ISSUE TITLE
smallrye-mutiny-vertx-kafka-client KafkaConsumer missing endOffsets(Set<TopicPartition> topicPartitions) method

### ISSUE THREAD

**Issue by gkozyryatskyy** [smallrye/smallrye-mutiny-vertx-bindings#724]
Artifact: `smallrye-mutiny-vertx-kafka-client`
Class: `io.vertx.mutiny.kafka.client.consumer.KafkaConsumer`
Missing Method: `endOffsets(Set<TopicPartition> topicPartitions) `

There is an `endOffsets` with `TopicPartition` parameter, but there is no `endOffsets` with `Set<TopicPartition>`

**Comment by cescoffier** [comment]
Can you report the issue in the Vert.x Kafka client project? The method in question is annotated with ` @GenIgnore`, meaning we don't see it during the generation. 

Also, in general, I recommend not using the Vert.x Kafka client as it does not handle rebalance correctly.

**Comment by gkozyryatskyy** [comment]
> Can you report the issue in the Vert.x Kafka client project? The method in question is annotated with ` @GenIgnore`, meaning we don't see it during the generation.
> 
> Also, in general, I recommend not using the Vert.x Kafka client as it does not handle rebalance correctly.

Thank you for the reply! I opened the issue in vertx repo.
But can you be more specific regarding rebalancing issue? Maybe you have a link to the bag, or something?
