### ISSUE TITLE
Update with recent Vert.x web template engines, drop MVEL

### ISSUE THREAD

**Issue by jponge** [smallrye/smallrye-mutiny-vertx-bindings#831]

**Comment by magicprinc** [comment]
It is time to replace it with Groovy-Templates!

https://docs.groovy-lang.org/docs/next/html/documentation/template-engines.html

Simpler and faster than MVEL

**Comment by magicprinc** [comment]
@cescoffier 
BTW
MVEL 'org.mvel:mvel2:2.5.0.Final' works fine with JDK 21.0.1

``'assertEquals("= 4 21.0.1", TemplateRuntime.eval("= @{1+1+x} @{System.getProperty('java.version')}", Map.of("x", 2)));```

**Comment by magicprinc** [comment]
I have create Groovy Template Engine for Vert.x

https://github.com/vert-x3/vertx-web/issues/2522

https://github.com/vert-x3/vertx-web/pull/2521

**Comment by tsegismont** [comment]
> @vietj and @tsegismont The reason for MVEL is simple: it does not work with Java 21.

Actually this was fixed by https://github.com/vert-x3/vertx-web/issues/2484
