### ISSUE TITLE
Vert.x 4.5 support

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-mutiny-vertx-bindings#852]
As you know ;-)
Vert.x 4.5 is released (Amazing, BTW)
Could you make compatible mutiny-vert.x binding please 🙏

**Comment by cescoffier** [comment]
Unfortunately, this Vert.x release contains a few breaking changes:


## Incompatible changes in vertx-mutiny-core
[cols="1,1,1,1", options="header"]
|===
| Element | Classification | Criticality | Description

| `method io.smallrye.mutiny.Uni<java.lang.Void> io.vertx.mutiny.core.http.HttpClient::updateSSLOptions(io.vertx.core.net.SSLOptions)` a|
* Source: BREAKING
 * Binary: NON_BREAKING | error | The return type changed from 'io.smallrye.mutiny.Uni<java.lang.Void>' to 'io.smallrye.mutiny.Uni<java.lang.Boolean>'.

| `method java.lang.Void io.vertx.mutiny.core.http.HttpClient::updateSSLOptionsAndAwait(io.vertx.core.net.SSLOptions)` a|
* Source: POTENTIALLY_BREAKING
 * Binary: BREAKING | error | The return type changed from 'java.lang.Void' to  'java.lang.Boolean'.

| `method io.smallrye.mutiny.Uni<java.lang.Void> io.vertx.mutiny.core.http.HttpServer::updateSSLOptions(io.vertx.core.net.SSLOptions)` a|
* Source: BREAKING
 * Binary: NON_BREAKING | error | The return type changed from 'io.smallrye.mutiny.Uni<java.lang.Void>' to 'io.smallrye.mutiny.Uni<java.lang.Boolean>'.

| `method java.lang.Void io.vertx.mutiny.core.http.HttpServer::updateSSLOptionsAndAwait(io.vertx.core.net.SSLOptions)` a|
* Source: POTENTIALLY_BREAKING
 * Binary: BREAKING | error | The return type changed from 'java.lang.Void' to  'java.lang.Boolean'.

| `method io.vertx.mutiny.core.http.WebSocketBase io.vertx.mutiny.core.http.ServerWebSocket::writePingAndForget(io.vertx.mutiny.core.buffer.Buffer)` a|
* Source: NON_BREAKING
 * Binary: BREAKING | error | The return type changed covariantly from 'io.vertx.mutiny.core.http.WebSocketBase' to 'io.vertx.mutiny.core.http.ServerWebSocket'.

| `method io.vertx.mutiny.core.http.WebSocketBase io.vertx.mutiny.core.http.ServerWebSocket::writePongAndForget(io.vertx.mutiny.core.buffer.Buffer)` a|
* Source: NON_BREAKING
 * Binary: BREAKING | error | The return type changed covariantly from 'io.vertx.mutiny.core.http.WebSocketBase' to 'io.vertx.mutiny.core.http.ServerWebSocket'.

| `method io.vertx.mutiny.core.http.WebSocketBase io.vertx.mutiny.core.http.WebSocket::writePingAndForget(io.vertx.mutiny.core.buffer.Buffer)` a|
* Source: NON_BREAKING
 * Binary: BREAKING | error | The return type changed covariantly from 'io.vertx.mutiny.core.http.WebSocketBase' to 'io.vertx.mutiny.core.http.WebSocket'.

| `method io.vertx.mutiny.core.http.WebSocketBase io.vertx.mutiny.core.http.WebSocket::writePongAndForget(io.vertx.mutiny.core.buffer.Buffer)` a|
* Source: NON_BREAKING
 * Binary: BREAKING | error | The return type changed covariantly from 'io.vertx.mutiny.core.http.WebSocketBase' to 'io.vertx.mutiny.core.http.WebSocket'.

| `method io.smallrye.mutiny.Uni<java.lang.Void> io.vertx.mutiny.core.net.NetClient::updateSSLOptions(io.vertx.core.net.SSLOptions)` a|
* Source: BREAKING
 * Binary: NON_BREAKING | error | The return type changed from 'io.smallrye.mutiny.Uni<java.lang.Void>' to 'io.smallrye.mutiny.Uni<java.lang.Boolean>'.

| `method java.lang.Void io.vertx.mutiny.core.net.NetClient::updateSSLOptionsAndAwait(io.vertx.core.net.SSLOptions)` a|
* Source: POTENTIALLY_BREAKING
 * Binary: BREAKING | error | The return type changed from 'java.lang.Void' to  'java.lang.Boolean'.

| `method io.smallrye.mutiny.Uni<java.lang.Void> io.vertx.mutiny.core.net.NetServer::updateSSLOptions(io.vertx.core.net.SSLOptions)` a|
* Source: BREAKING
 * Binary: NON_BREAKING | error | The return type changed from 'io.smallrye.mutiny.Uni<java.lang.Void>' to 'io.smallrye.mutiny.Uni<java.lang.Boolean>'.

| `method java.lang.Void io.vertx.mutiny.core.net.NetServer::updateSSLOptionsAndAwait(io.vertx.core.net.SSLOptions)` a|
* Source: POTENTIALLY_BREAKING
 * Binary: BREAKING | error | The return type changed from 'java.lang.Void' to  'java.lang.Boolean'.

|===
'''

Also, we expect more 4.4.x releases as the integration of Vert.x 4.5 in Quarkus is not going to happen before January. 

I'm going to prepare a branch, I will see with @jponge how to proceed.

**Comment by cescoffier** [comment]
See https://github.com/smallrye/smallrye-mutiny-vertx-bindings/pull/853.

**Comment by cescoffier** [comment]
Fixed in #853.
