### ISSUE TITLE
expecting() missing in Vertx WebClient

### ISSUE THREAD

**Issue by sschellh** [smallrye/smallrye-mutiny-vertx-bindings#989]
In the latest Quarkus version, the method
public io.vertx.mutiny.ext.web.client.HttpRequest<T> expect(io.vertx.mutiny.ext.web.client.predicate.ResponsePredicate predicate)
is deprecated.

According to the vert.x documentation (https://vertx.io/docs/vertx-web-client/java/), one shall use expecting instead.
However, this method seems not to be available in Quarkus.

**Comment by jponge** [comment]
Note: `expecting` is a method for Vert.x `Future<T>`, but since we wrap `Future`-returning methods to `Uni`, this requires further investigations.

**Comment by jponge** [comment]
To support cases like https://vertx.io/docs/apidocs/io/vertx/core/http/HttpResponseExpectation.html we'd need:

- a generator of Mutiny (or Rx, same issue) APIs wrapping, say, `HttpResponseExpectations` that is get called on build (hard-coded paths, but at least the adapters are generated and not copied)
- an adapter class to return "expectation operators" that are then `.plug(...)`-ed into `Uni`.

/cc @tsegismont

**Comment by jponge** [comment]
Rx PR https://github.com/vert-x3/vertx-rx/pull/317
